steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-west1-docker.pkg.dev/qwiklabs-gcp-01-a84b0664f0c4/my-repository/sample-app:v1.0', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/qwiklabs-gcp-01-a84b0664f0c4/my-repository/sample-app:v1.0']
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=dev/deployment.yaml
  - --image=us-west1-docker.pkg.dev/qwiklabs-gcp-01-a84b0664f0c4/my-repository/sample-app:v1.0
  - --location=us-west1-c
  - --cluster=hello-cluster
  - --namespace=dev
images:
- 'us-west1-docker.pkg.dev/qwiklabs-gcp-01-a84b0664f0c4/my-repository/sample-app:v1.0'
